//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ReadFile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadFile", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ReadFileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GimmeCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GimmeCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GimmeCode", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GimmeCodeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OddNumbers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int[] OddNumbers(int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OddNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<int[]> OddNumbersAsync(int n);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ConsoleApplication2.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ConsoleApplication2.ServiceReference1.WebService1Soap>, ConsoleApplication2.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld(string name) {
            return base.Channel.HelloWorld(name);
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync(string name) {
            return base.Channel.HelloWorldAsync(name);
        }
        
        public string ReadFile() {
            return base.Channel.ReadFile();
        }
        
        public System.Threading.Tasks.Task<string> ReadFileAsync() {
            return base.Channel.ReadFileAsync();
        }
        
        public string GimmeCode() {
            return base.Channel.GimmeCode();
        }
        
        public System.Threading.Tasks.Task<string> GimmeCodeAsync() {
            return base.Channel.GimmeCodeAsync();
        }
        
        public int[] OddNumbers(int n) {
            return base.Channel.OddNumbers(n);
        }
        
        public System.Threading.Tasks.Task<int[]> OddNumbersAsync(int n) {
            return base.Channel.OddNumbersAsync(n);
        }
    }
}
